### ISSUE TITLE
Leiningen : 라이닝겐 -> 라이닝언

### ISSUE THREAD

**Issue by guruma** [clojure-kr/translation#5]
저희가 찾아본 바로는 미국식이나 독일식 발음 모두 '라이닝언'이었습니다. (독일식은 '라이닝겐'인 줄 알았는데, 확인해보니 좀 뜨악했다는...)

**Comment by ksseono** [comment]
@guruma  네 라이닝언이 맞는 듯 합니다. 저도 반영하도록 하겠습니다. living clojure에서도 라이닝언으로 쓰시나요?

**Comment by guruma** [comment]
넵. 저희도 그렇게 했습니다.
2015. 11. 12. 오후 6:40에 "Seonho Kim" notifications@github.com님이 작성:
