### ISSUE TITLE
단어가 사용되는 맥락이 있어야 할 듯 합니다.

### ISSUE THREAD

**Issue by guruma** [clojure-kr/translation#6]
단어가 사용되는 맥락이 있어야 할 듯 합니다.

예를 들어 'unification' 이라는 단어/용어가 어디서 어떻게 사용되는지 알 수 없어서 적절한 번역어를 생각하기가 어렵습니다.

**Comment by ksseono** [comment]
@guruma the joy of clojure의 clojure/core.logic 설명을 위해 사용된 단어로, 논리 프로그래밍에서 사용되는 용어인데, 저도 맥락을 완전히 파악하지 못한 상태에서 사용했던 대역어입니다. '단일화'가 통상적인 단어여서 대체하려 합니다. 

참고링크 - http://www.aistudy.co.kr/expert/logic_lee.htm#_bookmark_1c3c328
